languageCode = 'en-us'
title = 'Slonser Notes'
theme = 'archie'

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode â†’ light,dark or auto
	featherIconsCDN=true
	subtitle = "Slonser Notes."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Slonser"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/slonser_"

[[params.social]]
name = "Telegram"
icon = "Telegram"
url = "https://t.me/Slonser"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"